apiVersion: v1
kind: Pod
metadata:
  labels:
    run: licaodecasa
  name: licaodecasa
spec:
  containers:
    - image: nginx
      name: webserver
      volumeMounts:
        - mountPath: /giropops
          name: primeiro-emptydir
      resources:
        requests:
          cpu: "0.5"
          memory: "64Mi"
        limits:
          cpu: "1"
          memory: "128Mi"
    - image: alpine
      name: pod-sleeped
      volumeMounts:
        - mountPath: /teste
          name: segundo-emptydir
      resources:
        requests:
          cpu: "0.3"
          memory: "64Mi"
        limits:
          cpu: "0.5"
          memory: "128Mi"
      args: ["sleep", "1800"]
      
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: primeiro-emptydir
      emptyDir:
        sizeLimit: 256Mi
    - name: segundo-emptydir
      emptyDir:
        sizeLimit: 128Mi
