apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: meu-primeiro-pvc
  name: meu-pvc
spec:
  storageClassName: giropops
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      storage: nfs