apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-test
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "VALOR REMOVIDO POR SEGURANÇA"


  # Para criar o valor do campo .dockerconfigjson, use o comando:
  # PASSO1: echo -n 'seu-usuario:seu-token-ou-senha' | base64
  # PASSO2: echo -n '{"auths":{"https://index.docker.io/v1/":{"auth":"VALOR_DO_PASSO_1"}}}' | base64 -w 0
  # O RESULTADO DO PASSO2 É O VALOR QUE VOCÊ DEVE COLOCAR NO CAMPO .dockerconfigjson