apiVersion: v1
kind: Pod
metadata:
  name: "giropops-container"
spec:
  containers:
  - name: giropops-container
    image: "nginx:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: primeiro-secret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: primeiro-secret
            key: password
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always